package system

import (
	"errors"
	"net"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// networkFixture is a box with four interfaces as sysfs shows them - eth0 up at 1000/full with
// the default route, eth1 administratively up without a cable, wlan0 on Wi-Fi without a speed,
// a container's veth - plus a bridge, the IPv6 addresses the kernel lists for eth0 and the two
// routing tables.
func networkFixture(t *testing.T) Root {
	t.Helper()
	r := rootWith(t, map[string]string{
		"etc/config/netconfig": "HOSTNAME=openccu\nMODE=DHCP\n",
		// eth0: a PCI NIC at a gigabit
		"sys/class/net/eth0/address":              "dc:a6:32:01:02:03\n",
		"sys/class/net/eth0/operstate":            "up\n",
		"sys/class/net/eth0/carrier":              "1\n",
		"sys/class/net/eth0/speed":                "1000\n",
		"sys/class/net/eth0/duplex":               "full\n",
		"sys/class/net/eth0/mtu":                  "1500\n",
		"sys/class/net/eth0/type":                 "1\n",
		"sys/class/net/eth0/ifindex":              "2\n",
		"sys/class/net/eth0/iflink":               "2\n",
		"sys/class/net/eth0/uevent":               "INTERFACE=eth0\nIFINDEX=2\n",
		"sys/class/net/eth0/statistics/rx_bytes":  "123456789\n",
		"sys/class/net/eth0/statistics/tx_bytes":  "98765\n",
		"sys/class/net/eth0/statistics/rx_errors": "0\n",
		"sys/class/net/eth0/statistics/tx_errors": "1\n",
		// eth1: up, no cable - the kernel's speed and duplex for a missing link
		"sys/class/net/eth1/address":   "dc:a6:32:01:02:04\n",
		"sys/class/net/eth1/operstate": "down\n",
		"sys/class/net/eth1/carrier":   "0\n",
		"sys/class/net/eth1/speed":     "-1\n",
		"sys/class/net/eth1/duplex":    "unknown\n",
		"sys/class/net/eth1/mtu":       "1500\n",
		"sys/class/net/eth1/type":      "1\n",
		// wlan0: Wi-Fi answers no speed at all
		"sys/class/net/wlan0/address":   "dc:a6:32:01:02:05\n",
		"sys/class/net/wlan0/operstate": "up\n",
		"sys/class/net/wlan0/carrier":   "1\n",
		"sys/class/net/wlan0/mtu":       "1500\n",
		"sys/class/net/wlan0/type":      "1\n",
		"sys/class/net/wlan0/uevent":    "DEVTYPE=wlan\nINTERFACE=wlan0\n",
		// veth: no device, its link is the host's end
		"sys/class/net/eth9/address":   "bc:24:11:aa:bb:cc\n",
		"sys/class/net/eth9/operstate": "up\n",
		"sys/class/net/eth9/carrier":   "1\n",
		"sys/class/net/eth9/speed":     "10000\n",
		"sys/class/net/eth9/duplex":    "full\n",
		"sys/class/net/eth9/mtu":       "1500\n",
		"sys/class/net/eth9/type":      "1\n",
		"sys/class/net/eth9/ifindex":   "5\n",
		"sys/class/net/eth9/iflink":    "31\n",
		"sys/class/net/eth9/uevent":    "INTERFACE=eth9\nIFINDEX=5\n",
		// a bridge, administratively down: no carrier file answer
		"sys/class/net/br0/operstate": "down\n",
		"sys/class/net/br0/mtu":       "1500\n",
		"sys/class/net/br0/type":      "1\n",
		"sys/class/net/br0/uevent":    "DEVTYPE=bridge\nINTERFACE=br0\n",
		"sys/class/net/lo/operstate":  "unknown\n",
		// bonding_masters is a plain file next to the interfaces
		"sys/class/net/bonding_masters": "\n",
		"proc/net/if_inet6": "20010db8000100000000000000000011 02 40 00 80     eth0\n" +
			"20010db80001000012345678abcdef01 02 40 00 21     eth0\n" +
			"fd000000000000000000000000000011 02 40 00 80     eth0\n" +
			"fe80000000000000dea632fffe010203 02 40 20 80     eth0\n" +
			"fe80000000000000dea632fffe010205 03 40 20 c0    wlan0\n" +
			"00000000000000000000000000000001 01 80 10 80       lo\n",
		"proc/net/route": "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT\n" +
			"wlan0\t00000000\t0102A8C0\t0003\t0\t0\t600\t00000000\t0\t0\t0\n" +
			"eth0\t00000000\t0102A8C0\t0003\t0\t0\t100\t00000000\t0\t0\t0\n" +
			"eth0\t0002A8C0\t00000000\t0001\t0\t0\t100\t00FFFFFF\t0\t0\t0\n",
		"proc/net/ipv6_route": "00000000000000000000000000000000 00 00000000000000000000000000000000 00 fe800000000000000000000000000001 00000400 00000001 00000000 00000003     eth0\n" +
			"00000000000000000000000000000000 00 00000000000000000000000000000000 00 00000000000000000000000000000000 ffffffff 00000001 00000000 00200200       lo\n" +
			"20010db8000100000000000000000000 40 00000000000000000000000000000000 00 00000000000000000000000000000000 00000100 00000001 00000000 00000001     eth0\n",
		"proc/sys/net/ipv6/conf/all/disable_ipv6":  "0\n",
		"proc/sys/net/ipv6/conf/eth0/disable_ipv6": "0\n",
		"proc/sys/net/ipv6/conf/eth0/autoconf":     "1\n",
		"proc/sys/net/ipv6/conf/eth0/accept_ra":    "1\n",
		"proc/sys/net/ipv6/conf/eth1/disable_ipv6": "1\n",
		"proc/sys/net/ipv6/conf/eth1/autoconf":     "1\n",
		"proc/sys/net/ipv6/conf/eth1/accept_ra":    "1\n",
		"etc/resolv.conf":                          "# Generated by resolvconf\ndomain lan.example\nnameserver 192.168.2.1\nnameserver fd00::1\nnameserver 2001:db8:1::53\n",
	})
	mkdir := func(p string) {
		if err := os.MkdirAll(r.join(p), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	link := func(target, p string) {
		if err := os.Symlink(target, r.join(p)); err != nil {
			t.Fatal(err)
		}
	}
	mkdir("/sys/class/net/eth0/device")
	link("../../../../bus/pci/drivers/r8169", "/sys/class/net/eth0/device/driver")
	mkdir("/sys/class/net/eth1/device")
	link("../../../../bus/usb/drivers/r8152", "/sys/class/net/eth1/device/driver")
	mkdir("/sys/class/net/wlan0/device")
	mkdir("/sys/class/net/wlan0/wireless")
	link("../../../../bus/sdio/drivers/brcmfmac", "/sys/class/net/wlan0/device/driver")
	mkdir("/sys/class/net/br0/bridge")

	old := AddrsOf
	AddrsOf = func(name string) ([]net.Addr, error) {
		cidr := map[string][]string{
			"eth0":  {"192.168.2.20/24", "2001:db8:1::11/64"},
			"wlan0": {"192.168.2.21/24"},
			"eth9":  {"10.0.0.7/24"},
		}[name]
		if cidr == nil {
			return nil, errors.New("no such interface")
		}
		out := []net.Addr{}
		for _, c := range cidr {
			ip, n, _ := net.ParseCIDR(c)
			n.IP = ip
			out = append(out, n)
		}
		return out, nil
	}
	t.Cleanup(func() { AddrsOf = old })
	return r
}

func TestReadNetworkInterfaces(t *testing.T) {
	n := networkFixture(t)
	nw := n.ReadNetwork()
	byName := map[string]NetIface{}
	var names []string
	for _, i := range nw.Interfaces {
		byName[i.Name] = i
		names = append(names, i.Name)
	}
	if want := []string{"br0", "eth0", "eth1", "eth9", "wlan0"}; !reflect.DeepEqual(names, want) {
		t.Fatalf("interfaces %v, want %v (lo and bonding_masters left out)", names, want)
	}
	yes, no := true, false
	cases := []struct {
		name      string
		up        bool
		operstate string
		carrier   *bool
		speed     int
		duplex    string
		kind      string
		driver    string
		def       bool
		ipv4      []NetAddr
	}{
		{"eth0", true, "up", &yes, 1000, "full", "ethernet", "r8169", true, []NetAddr{{Address: "192.168.2.20", Prefix: 24}}},
		{"eth1", false, "down", &no, 0, "", "ethernet", "r8152", false, []NetAddr{}},
		{"wlan0", true, "up", &yes, 0, "", "wireless", "brcmfmac", false, []NetAddr{{Address: "192.168.2.21", Prefix: 24}}},
		{"eth9", true, "up", &yes, 10000, "full", "veth", "", false, []NetAddr{{Address: "10.0.0.7", Prefix: 24}}},
		{"br0", false, "down", nil, 0, "", "bridge", "", false, []NetAddr{}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			i := byName[c.name]
			if i.Up != c.up || i.Operstate != c.operstate || i.Speed != c.speed || i.Duplex != c.duplex || i.Kind != c.kind || i.Driver != c.driver || i.DefaultRoute != c.def {
				t.Errorf("got up=%v operstate=%q speed=%d duplex=%q kind=%q driver=%q default=%v", i.Up, i.Operstate, i.Speed, i.Duplex, i.Kind, i.Driver, i.DefaultRoute)
			}
			if !reflect.DeepEqual(i.Carrier, c.carrier) {
				t.Errorf("carrier %v, want %v", i.Carrier, c.carrier)
			}
			if !reflect.DeepEqual(i.IPv4, c.ipv4) {
				t.Errorf("ipv4 %+v, want %+v", i.IPv4, c.ipv4)
			}
			if i.MTU != 1500 {
				t.Errorf("mtu %d", i.MTU)
			}
			if i.IPv6 == nil {
				t.Error("ipv6 must be a list, never null")
			}
		})
	}
	eth0 := byName["eth0"]
	if eth0.MAC != "dc:a6:32:01:02:03" {
		t.Errorf("mac %q", eth0.MAC)
	}
	if s := eth0.Statistics; s == nil || s.RxBytes != 123456789 || s.TxBytes != 98765 || s.TxErrors != 1 {
		t.Errorf("statistics %+v", s)
	}
	if byName["eth1"].Statistics != nil {
		t.Error("no counters in sysfs, none in the answer")
	}
	if e := eth0.IPv6Enabled; e == nil || !*e || eth0.IPv6Autoconf == nil || !*eth0.IPv6Autoconf {
		t.Errorf("eth0 ipv6 on %v, autoconf %v", e, eth0.IPv6Autoconf)
	}
	if e := byName["eth1"].IPv6Enabled; e == nil || *e {
		t.Errorf("eth1 has IPv6 switched off: %v", e)
	}
	if byName["wlan0"].IPv6Enabled != nil {
		t.Error("no conf file, no answer")
	}
}

func TestReadNetworkIPv6(t *testing.T) {
	nw := networkFixture(t).ReadNetwork()
	var eth0, wlan0 NetIface
	for _, i := range nw.Interfaces {
		switch i.Name {
		case "eth0":
			eth0 = i
		case "wlan0":
			wlan0 = i
		}
	}
	want := []NetAddr{
		{Address: "2001:db8:1::11", Prefix: 64, Scope: "global", Flags: []string{"permanent"}},
		{Address: "2001:db8:1:0:1234:5678:abcd:ef01", Prefix: 64, Scope: "global", Flags: []string{"temporary", "deprecated"}},
		{Address: "fd00::11", Prefix: 64, Scope: "unique-local", Flags: []string{"permanent"}},
		{Address: "fe80::dea6:32ff:fe01:203", Prefix: 64, Scope: "link-local", Flags: []string{"permanent"}},
	}
	if !reflect.DeepEqual(eth0.IPv6, want) {
		t.Errorf("eth0 ipv6\n got %+v\nwant %+v", eth0.IPv6, want)
	}
	if len(wlan0.IPv6) != 1 || wlan0.IPv6[0].Scope != "link-local" || !reflect.DeepEqual(wlan0.IPv6[0].Flags, []string{"tentative", "permanent"}) {
		t.Errorf("wlan0 ipv6 %+v", wlan0.IPv6)
	}
	st := nw.IPv6State
	if !st.Available || !st.Enabled || st.Gateway != "fe80::1" || st.GatewayInterface != "eth0" {
		t.Errorf("ipv6 state %+v", st)
	}
	if !reflect.DeepEqual(st.DNS, []string{"fd00::1", "2001:db8:1::53"}) {
		t.Errorf("ipv6 dns %v", st.DNS)
	}
}

// A kernel without IPv6 has no if_inet6: the addresses come from the live lookup without flags, and
// IPv6 is neither available nor on.
func TestReadNetworkWithoutIfInet6(t *testing.T) {
	r := networkFixture(t)
	if err := os.Remove(r.join("/proc/net/if_inet6")); err != nil {
		t.Fatal(err)
	}
	nw := r.ReadNetwork()
	for _, i := range nw.Interfaces {
		if i.Name != "eth0" {
			continue
		}
		if len(i.IPv6) != 1 || i.IPv6[0].Address != "2001:db8:1::11" || i.IPv6[0].Scope != "global" || i.IPv6[0].Flags != nil {
			t.Errorf("fallback ipv6 %+v", i.IPv6)
		}
	}
	if nw.IPv6State.Available || nw.IPv6State.Enabled {
		t.Errorf("ipv6 state %+v", nw.IPv6State)
	}
}

// The IPv4 default route decides which interface carries it; without one the IPv6 route does.
func TestDefaultRouteInterface(t *testing.T) {
	r := networkFixture(t)
	if err := os.WriteFile(r.join("/proc/net/route"), []byte("Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	for _, i := range r.ReadNetwork().Interfaces {
		if i.DefaultRoute != (i.Name == "eth0") {
			t.Errorf("%s default %v", i.Name, i.DefaultRoute)
		}
	}
	_ = os.Remove(r.join("/proc/net/ipv6_route"))
	for _, i := range r.ReadNetwork().Interfaces {
		if i.DefaultRoute {
			t.Errorf("%s carries no default route", i.Name)
		}
	}
	if _, err := os.Stat(filepath.Join(string(r), "proc/net/route")); err != nil {
		t.Fatal(err)
	}
}
