// Task 38: a certificate, its key and the CA that signed it, for the stub's preview and the
// Playwright spec that pastes them. Made once with openssl (P-256, CN=ccu.example.org with the
// SANs ccu.example.org and ccu.lan, valid until 2045; the CA until 2046); nothing signs anything
// with these outside the test rig.
export const CERT = `-----BEGIN CERTIFICATE-----
MIIB2zCCAYGgAwIBAgIUWzr6Cbw1WwCYDjxF1I17ih9vdG0wCgYIKoZIzj0EAwIw
NDEVMBMGA1UEAwwMU3R1YiBUZXN0IENBMRswGQYDVQQKDBJvcGVuY2N1LWxpdGUg
dGVzdHMwHhcNMjYwOTA5MTYyOTA2WhcNNDUxMTA4MTYyOTA2WjApMRgwFgYDVQQD
DA9jY3UuZXhhbXBsZS5vcmcxDTALBgNVBAoMBEhvbWUwWTATBgcqhkjOPQIBBggq
hkjOPQMBBwNCAATMHtgujnsHHci47M2ZS8c34/ULlBDBtvglHliCRHHeRAFnxd6S
8UJxGxynI4vybGjm6mYtWVDw0F47Z7IDhUiXo3wwejAjBgNVHREEHDAagg9jY3Uu
ZXhhbXBsZS5vcmeCB2NjdS5sYW4wEwYDVR0lBAwwCgYIKwYBBQUHAwEwHQYDVR0O
BBYEFF9LgKla6GeSSZ14YBQgGxJJVkvyMB8GA1UdIwQYMBaAFGZuXtc9zddZLHGe
x2we5hC0FM5CMAoGCCqGSM49BAMCA0gAMEUCIDyDIS4oWiOsCmUW6WJjuruFnVJy
YLQ7a/36UyD9P8DNAiEAgtrl50yM0eXvSSd0bsuF+bPkjGP9WaaH3cwRP1Fp6FI=
-----END CERTIFICATE-----
`;
export const KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgn2DVHJMQssqY293E
WkDOTZD7LD9EIS+blkiPTHVS2kShRANCAATMHtgujnsHHci47M2ZS8c34/ULlBDB
tvglHliCRHHeRAFnxd6S8UJxGxynI4vybGjm6mYtWVDw0F47Z7IDhUiX
-----END PRIVATE KEY-----
`;
export const CA = `-----BEGIN CERTIFICATE-----
MIIBvTCCAWOgAwIBAgIUHcJnAMM5aYZ4+EkDmHmBanY5VlkwCgYIKoZIzj0EAwIw
NDEVMBMGA1UEAwwMU3R1YiBUZXN0IENBMRswGQYDVQQKDBJvcGVuY2N1LWxpdGUg
dGVzdHMwHhcNMjYwOTA5MTYyOTA2WhcNNDYwOTA0MTYyOTA2WjA0MRUwEwYDVQQD
DAxTdHViIFRlc3QgQ0ExGzAZBgNVBAoMEm9wZW5jY3UtbGl0ZSB0ZXN0czBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABG2p3tKWzhF1quXQamsm1vuuh8sCgTUixdjq
jkFofTVmhxFWiECt4i3VwGds9cySDh+SEafyctdkL09AC5DGEwyjUzBRMB0GA1Ud
DgQWBBRmbl7XPc3XWSxxnsdsHuYQtBTOQjAfBgNVHSMEGDAWgBRmbl7XPc3XWSxx
nsdsHuYQtBTOQjAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIDl0
ligEbGyhj+tef4842VKyxf7KAx0haHrx0y+NosDzAiEA62RDZynTmuKGi1dmJ+3o
qXNPriQjsx5cgDvxEbpmfQ8=
-----END CERTIFICATE-----
`;
// a key that is not the certificate's, for the mismatch preview
export const OTHER_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgq5tBIKj91NhvVfq2
/k0lKAP9L9co+w8Eewe32op2UxChRANCAAT4iUB4y8jLjIdsE9N4++989eF+RSG1
1XYnxMlFphdm/qKSrD8+h7ZegpFab7chOclYZljE6STTi2RgbB71h7Y7
-----END PRIVATE KEY-----
`;
